# Generated by Django 5.1.2 on 2024-11-04 11:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Drink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("yen", models.IntegerField()),
                ("is_out_of_order", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="Treat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("yen", models.IntegerField()),
                ("is_out_of_order", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("register_datetime", models.DateTimeField()),
                ("is_suger", models.BooleanField(default=False)),
                ("is_milk", models.BooleanField(default=False)),
                ("is_served", models.BooleanField(default=False)),
                (
                    "drink",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="jazzcafe.drink",
                    ),
                ),
                (
                    "treat",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="jazzcafe.treat",
                    ),
                ),
            ],
        ),
    ]
