# Generated by Django 5.1.2 on 2024-11-06 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jazzcafe", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="table_number",
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
